# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

php:
  image:
    repository: ~
    tag: ~
    pullPolicy: IfNotPresent
  env: prod
  debug: '0'
  secret: ""
  corsAllowOrigin: "^https?://.*?\\.example\\.com$"
  trustedHosts: "^.*\\.example\\.com$"
  trustedProxies:
    - "127.0.0.1"
    - "10.0.0.0/8"
    - "172.0.0.0/8"
    - "192.168.0.0/16"
  mailer:
    email: 'noreply@example.com'
    dsn: 'null://null'
  jwt:
    secret: ''
    public: ''
    passphrase: ''
    samesite: 'lax'
  mercure:
    jwt:
      algorithm: 'hmac.sha256'
  blackfire:
    id: ''
    token: ''
  databaseLoadFixtures: false
  # base64 encoded
  databaseSSL:
    ca: ~
    key: ~
    cert: ~
    mode: prefer
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  gcloud:
    jsonKey: my-dummy-very-long-json-key-placeholder-value
    bucket: bucket-name
  admin:
    username: ~
    password: ~
    email: ~

caddy:
  globalDirectives: ''
  image:
    repository: ~
    tag: ~
    pullPolicy: IfNotPresent
  # Mercure: You need the managed or the On Premise version to deploy more than one pod: https://mercure.rocks/docs/hub/cluster
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

# api deployment - both caddy and php containers
api:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  service:
    type: ClusterIP
    port: 80

# You may prefer using the managed version in production: https://mercure.rocks
mercure:
  corsOrigin: '*'
  jwtSecret: ~
  jwtKey:
    subscriber:
      key: 'my-key-that-must-be-at-least-256-bits'
      algorithm: ~
    publisher:
      key: 'my-key-that-must-be-at-least-256-bits'
      algorithm: ~
  publicUrl: ~
  url: ~
  # need paid managed solution to enable this feature for replication
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# can be enabled for feature branches to avoid using prod database
postgresql:
  enabled: false
  image:
    tag: ~
  auth:
    postgresPassword: pg_root_password
    username: pg_user
    password: pg_password
    database: pg_database
  # if external and enabled is false - should be external in production
  url: 'pgsql://'
  primary:
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 1m
  readReplicas:
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 20m
  
varnish:
  enabled: true
  image:
    repository: ~
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      memory: 80Mi
      cpu: 100m
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

blackfire:
  replicaCount: 1
  enabled: true
  image:
    repository: blackfire/blackfire
    tag: latest
    pullPolicy: Always
  server:
    id: ''
    token: ''
  resources:
    limits:
      memory: 64Mi
      cpu: 50m
    # requests:
    #   cpu: 100m
    #   memory: 128Mi


ingress:
  enabled: false
  annotations:
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  hosts:
    - host: api.example.com
      paths: [ ]
  tls: [ ]
    #  - secretName: api-example-tls
    #    hosts:
    #      - api.example.com

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: { }
  # fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: { }

tolerations: [ ]

affinity: { }

podAnnotations: { }
