{{- $name := "api" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
{{- $fullName := include "cwa.fullname" . -}}
{{- $primaryHost := index .Values.ingress.hosts 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "cwa.labels" $data | nindent 4 }}
  annotations:
    {{- include "cwa.annotations" $data | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "cwa.selectorLabels" $data | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "cwa.annotations" $data | nindent 8 }}
      labels:
        {{- include "cwa.selectorLabels" $data | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cwa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-caddy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.caddy.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: :80
            - name: BROWSER_SERVER_NAME
              value: {{ $primaryHost.host | quote }}
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: mercure-publisher-jwt-key
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: mercure-subscriber-jwt-key
            - name: MERCURE_PUBLISHER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mercure-publisher-jwt-algorithm
            - name: MERCURE_SUBSCRIBER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mercure-subscriber-jwt-algorithm
            - name: VARNISH_UPSTREAM
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: varnish-upstream
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP
          volumeMounts:
            - mountPath: /var/run/php
              name: php-socket
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            httpGet:
              path: /health-check
              port: http
              httpHeaders:
                - name: Host
                  value: 'caddy-probe.local'
                - name: X-Kubernetes-Liveness
                  value: {{ $fullName }}
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            httpGet:
              path: /health-check
              port: http
              httpHeaders:
                - name: Host
                  value: 'caddy-probe.local'
                - name: X-Kubernetes-Readiness
                  value: {{ $fullName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          env:
            - name: DATABASE_LOAD_FIXTURES
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: database-load-fixtures
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: php-app-debug
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: php-cors-allow-origin
            - name: VARNISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: varnish-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: database-url
            - name: MERCURE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mercure-url
            - name: MERCURE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mercure-public-url
            - name: MERCURE_JWT_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: mercure-jwt-secret
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: jwt-secret
            - name: JWT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: jwt-public
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: jwt-passphrase
            - name: MAILER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mailer-email
            - name: MAILER_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: mailer-dsn
            - name: BLACKFIRE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: blackfire-client-id
            - name: BLACKFIRE_CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: blackfire-client-token
          volumeMounts:
            - mountPath: /var/run/php
              name: php-socket
          startupProbe:
            exec:
              command:
                - docker-healthcheck
            failureThreshold: 40
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
                - docker-healthcheck
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - docker-healthcheck
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: php-socket
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
