{{- $name := "api" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
{{- $fullName := include "cwa.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "cwa.labels" $data | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cwa.selectorLabels" $data | nindent 4 }}
