apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cwa.fullname" . }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cwa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cwa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cwa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-caddy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.caddy.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: :80
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-publisher-jwt-key
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-subscriber-jwt-key
            - name: MERCURE_PUBLISHER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-publisher-jwt-algorithm
            - name: MERCURE_SUBSCRIBER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-subscriber-jwt-algorithm
            - name: VARNISH_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: varnish-service
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP
          volumeMounts:
            - mountPath: /var/run/php
              name: php-socket
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
              httpHeaders:
                - name: Host
                  value: 'caddy-probe'
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
              httpHeaders:
                - name: Host
                  value: 'caddy-probe'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          env:
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-app-debug
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-cors-allow-origin
            - name: VARNISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: varnish-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: database-url
            - name: MERCURE_PUBLISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-publish-url
            - name: MERCURE_SUBSCRIBE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-subscribe-url
            - name: MERCURE_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-jwt-token
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: jwt-secret
            - name: JWT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: jwt-public
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: jwt-passphrase
            - name: MAILER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mailer-email
            - name: MAILER_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mailer-dsn
            - name: BLACKFIRE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: blackfire-client-id
            - name: BLACKFIRE_CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: blackfire-client-token
          volumeMounts:
            - mountPath: /var/run/php
              name: php-socket
          readinessProbe:
            exec:
              command:
                - docker-healthcheck
            initialDelaySeconds: 120
            periodSeconds: 3
          livenessProbe:
            exec:
              command:
                - docker-healthcheck
            initialDelaySeconds: 120
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: php-socket
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
