{{- if .Values.blackfire.enabled -}}
{{- $name := "blackfire" -}}
{{- $fullName := include "cwa.fullname" . -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "cwa.labels" $data | nindent 4 }}
  annotations:
    {{- include "cwa.annotations" $data | nindent 4 }}
spec:
  replicas: {{ .Values.blackfire.replicaCount }}
  selector:
    matchLabels:
      {{- include "cwa.selectorLabels" $data | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cwa.selectorLabels" $data | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "cwa.annotations" $data | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cwa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ $name }}
          image: "{{ .Values.blackfire.image.repository }}:{{ .Values.blackfire.image.tag }}"
          imagePullPolicy: {{ .Values.blackfire.image.pullPolicy }}
          ports:
            - name: agent
              containerPort: 8707
              protocol: TCP
          livenessProbe:
              tcpSocket:
                  port: agent
          readinessProbe:
              tcpSocket:
                  port: agent
          env:
            - name: BLACKFIRE_SERVER_ID
              valueFrom:
                  configMapKeyRef:
                      name: {{ $fullName }}
                      key: blackfire-server-id
            - name: BLACKFIRE_SERVER_TOKEN
              valueFrom:
                  secretKeyRef:
                      name: {{ $fullName }}
                      key: blackfire-server-token
          resources:
            {{- toYaml .Values.blackfire.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
