{{- if .Values.blackfire.enabled -}}
{{- $name := "blackfire" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}-{{ $name }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: agent
      protocol: TCP
      name: agent
  selector:
    {{- include "api.selectorLabels" $data | nindent 4 }}
{{- end -}}
