{{- if .Values.blackfire.enabled -}}
{{- $name := "blackfire" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Service
metadata:
  # must use a static name as this is hard-coded into the Dockerfile for the PHP probe. Must be 'blackfire'
  name: {{ $name }}
  labels:
    {{- include "cwa.labels" $data | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8707
      targetPort: agent
      protocol: TCP
      name: agent
  selector:
    {{- include "cwa.selectorLabels" $data | nindent 4 }}
{{- end -}}
