{{- if .Values.blackfire.enabled -}}
{{- $name := "blackfire" -}}
{{- $fullName := include "api.fullname" . -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}-{{ $name }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
  annotations:
    {{- include "api.annotations" $data | nindent 4 }}
spec:
  replicas: {{ .Values.varnish.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" $data | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" $data | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "api.annotations" $data | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ $name }}
          image: "{{ .Values.blackfire.image.repository }}:{{ .Values.blackfire.image.tag }}"
          imagePullPolicy: {{ .Values.blackfire.image.pullPolicy }}
          ports:
            - containerPort: 8707
          env:
            - name: BLACKFIRE_CLIENT_ID
              valueFrom:
                  configMapKeyRef:
                      name: {{ $fullName }}
                      key: blackfire-client-id
            - name: BLACKFIRE_CLIENT_TOKEN
              valueFrom:
                  secretKeyRef:
                      name: {{ $fullName }}
                      key: blackfire-client-token
            - name: BLACKFIRE_SERVER_ID
              valueFrom:
                  configMapKeyRef:
                      name: {{ $fullName }}
                      key: blackfire-server-id
            - name: BLACKFIRE_SERVER_TOKEN
              valueFrom:
                  secretKeyRef:
                      name: {{ $fullName }}
                      key: blackfire-server-token
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
