apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cwa.fullname" . }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
data:
  php-app-env: {{ .Values.php.env | quote }}
  php-app-debug: {{ .Values.php.debug | quote }}
  php-cors-allow-origin: {{ .Values.php.corsAllowOrigin | quote }}
  php-trusted-hosts: {{ .Values.php.trustedHosts | quote }}
  php-trusted-proxies: {{ join "," .Values.php.trustedProxies }}
  mercure-publish-url: {{ .Values.mercure.publishUrl | default "http://127.0.0.1/.well-known/mercure" | quote }}
  mercure-subscribe-url: {{ .Values.mercure.subscribeUrl | quote }}
  mercure-subscriber-jwt-algorithm: {{ .Values.mercure.jwtKey.subscriber.algorithm | quote }}
  mercure-publisher-jwt-algorithm: {{ .Values.mercure.jwtKey.publisher.algorithm | quote }}
  varnish-url: http://{{ include "cwa.fullname" . }}-varnish
  varnish-service: {{ include "cwa.fullname" . }}-varnish
  blackfire-client-id: {{ .Values.php.blackfire.id | quote }}
  blackfire-server-id: {{ .Values.blackfire.server.id | quote }}
  jwt-public: {{ .Values.php.jwt.public | quote }}
  mailer-email: {{ .Values.php.mailer.email | quote }}
