{{- $name := "php" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.varnish.enabled }}php{{ else }}{{ include "api.fullname" . }}-{{ $name }}{{ end }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
spec:
  type: {{ .Values.php.service.type }}
  ports:
    - port: {{ .Values.php.service.port }}
  selector:
    {{- include "api.selectorLabels" $data | nindent 4 }}
