{{- $fullName := include "cwa.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://postgres:%s@%s-postgresql:5432/%s?serverVersion=13&charset=utf8" .Values.postgresql.auth.postgresPassword .Release.Name .Values.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  blackfire-client-token: {{ .Values.php.blackfire.token | default "-" | b64enc | quote }}
  blackfire-server-token: {{ .Values.blackfire.server.token | default "-" | b64enc | quote }}
  jwt-secret: {{ .Values.php.jwt.secret | b64enc | quote }}
  jwt-passphrase: {{ .Values.php.jwt.passphrase | b64enc | quote }}
  mailer-dsn: {{ .Values.php.mailer.dsn | b64enc | quote }}
  mercure-subscriber-jwt-key: {{ .Values.mercure.jwtKey.subscriber.key | b64enc | quote }}
  mercure-publisher-jwt-key: {{ .Values.mercure.jwtKey.publisher.key | b64enc | quote }}
  database-ssl-ca: {{ .Values.php.databaseSSL.ca | quote }}
  database-ssl-cert: {{ .Values.php.databaseSSL.cert | quote }}
  database-ssl-key: {{ .Values.php.databaseSSL.key | quote }}
  gcloud-json: {{ .Values.php.gcloud.jsonKey | quote }}
  admin-username: {{ .Values.php.admin.username | b64enc | quote }}
  admin-password: {{ .Values.php.admin.password | b64enc | quote }}
  admin-email: {{ .Values.php.admin.email | b64enc | quote }}
