apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.php.databaseUrl | b64enc | quote }}
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-token: {{ .Values.php.mercure.jwtToken | b64enc | quote }}
