apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cwa.fullname" . }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=13&charset=utf8" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  blackfire-client-token: {{ .Values.php.blackfire.token | default "-" | b64enc | quote }}
  blackfire-server-token: {{ .Values.blackfire.server.token | default "-" | b64enc | quote }}
  jwt-secret: {{ .Values.php.jwt.secret | b64enc | quote }}
  jwt-passphrase: {{ .Values.php.jwt.passphrase | b64enc | quote }}
  mailer-dsn: {{ .Values.php.mailer.dsn | b64enc | quote }}
  mercure-subscriber-jwt-key: {{ .Values.mercure.jwtKey.subscriber.key | b64enc | quote }}
  mercure-publisher-jwt-key: {{ .Values.mercure.jwtKey.publisher.key | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | b64enc | quote }}
