{{- if .Values.vulcain.enabled -}}
{{- $name := "vulcain" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}-{{ $name }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
spec:
  replicas: {{ .Values.vulcain.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" $data | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" $data | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ $name }}
          image: "{{ .Values.vulcain.image.repository }}:{{ .Values.vulcain.image.tag }}"
          imagePullPolicy: {{ .Values.vulcain.image.pullPolicy }}
          env:
          - name: UPSTREAM
            value: {{ if .Values.varnish.enabled }}http://varnish{{ else }}http://nginx{{ end }}
          ports:
            - containerPort: 443
          livenessProbe:
            httpGet:
              path: /healthz
              port: 443
          readinessProbe:
            httpGet:
              path: /healthz
              port: 443
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
