{{- if .Values.vulcain.enabled -}}
{{- $name := "vulcain" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
{{- $fullName := include "api.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
  annotations:
    {{- include "api.annotations" $data | nindent 4 }}
spec:
  replicas: {{ .Values.vulcain.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" $data | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" $data | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "api.annotations" $data | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ $name }}
          image: "{{ .Values.vulcain.image.repository }}:{{ .Values.vulcain.image.tag }}"
          imagePullPolicy: {{ .Values.vulcain.image.pullPolicy }}
          env:
          - name: UPSTREAM
            value: "{{ if .Values.varnish.enabled }}http://{{ $fullName }}-varnish{{ else }}http://{{ $fullName }}-nginx{{ end }}.{{ .Release.Namespace }}.svc.cluster.local:{{ if .Values.varnish.enabled }}{{ .Values.varnish.service.port }}{{ else }}{{ .Values.nginx.service.port }}{{ end }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
