# Development environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_dev
    volumes:
      - ./api:/app
      - /app/var
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo # - CHECK WHETHER WE STILL NEED THIS PATH ARG (/srv/mercure-assets/)
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      # CADDY_GLOBAL_OPTIONS: "local_certs"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '800M'
        reservations:
          cpus: '0.5'
          memory: '600M'

  app:
    build:
      context: ./app
      target: dev
    volumes:
      - ./app:/srv/app:rw,cached
      - /srv/app/.pnpm-store
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NUXT_PUBLIC_CWA_API_URL: ${API_URL:-https://php.local}
      NUXT_PUBLIC_CWA_API_URL_BROWSER: ${API_URL_BROWSER:-https://localhost}
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
    links:
      - "php:php.local"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
