api_platform:
    # version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure: ~
    defaults:
      cache_headers:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
            xkey:
                glue: ', '
        public: true
    metadata_backward_compatibility_layer: false
