api_platform:
  version: 1.0.0
  # Mercure integration, remove if unwanted
  mercure: ~
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  formats:
    jsonld: ['application/ld+json']
    multipart: ['multipart/form-data']
  docs_formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  keep_legacy_inflector: true
  http_cache:
    invalidation:
      purger: 'api_platform.http_cache.purger.varnish.xkey'
      enabled: true
      urls: ['%env(CACHE_URL)%']
    public: true
  use_symfony_listeners: true
  defaults:
    #standard_put: true
    extra_properties:
      rfc_7807_compliant_errors: true
    cache_headers:
      max_age: 0
      shared_max_age: 60
      vary: ['Content-Type', 'Authorization']
      invalidation:
        xkey:
          glue: ' '
