liip_imagine:
  data_loader: silverback.api_components.liip_imagine.binary.loader
  cache: in_memory_cache_resolver
  filter_sets:
    thumbnail:
      jpeg_quality: 90
      png_compression_level: 0
      filters:
        thumbnail:
          size: [ 500, 500 ]
          mode: inset
