apiVersion: v2
name: cwa
description: A Helm chart for a CWA project
home: https://cwa.rocks
#icon: https://cwa.rocks/logo-250x250.png

# An 'application' chart (deployable), not a 'library'.
type: application

# The chart's version (SemVer); bump it when the chart changes.
version: 0.1.0

# The deployed application's version.
appVersion: 0.1.0

dependencies:
  - name: postgresql
    version: ~14.3.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
