# Default values for cwa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

php:
  admin:
    username: admin
    password: admin
    email: hello@cwa.rocks
  gcloud:
    jsonKey: "my-dummy-very-long-json-key-placeholder-value"
    bucket: "no-gcloud-bucket"
  image:
    repository: "chart-example.local/cwa/php"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  appEnv: prod
  appDebug: "0"
  appSecret: ""
  corsAllowOrigin: "^https?://.*?\\.chart-example\\.local$"
  trustedHosts: "^127\\.0\\.0\\.1|localhost|.*\\.chart-example\\.local$"
  trustedProxies:
    - "127.0.0.1"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  caddyGlobalOptions: "debug" # "auto_https off"
  apiSecretToken: ~
  mailer:
    dsn: ${MAILER_DSN:-"~"}
    email: ${MAILER_EMAIL:-"~"}
  jwt:
    secret: ''
    public: ''
    passphrase: ~
    samesite: 'lax'
  mercure:
    jwt:
      algorithm: ${MERCURE_JWT_ALGORITHM:-"hmac.sha256"}
  databaseSSL:
    ca: ${DATABASE_CA_CERT_B64}
    key: ${DATABASE_CLIENT_KEY_B64}
    cert: ${DATABASE_CLIENT_CERT_B64}
    mode: ${DATABASE_SSL_MODE:-"prefer"}

pwa:
  apiUrl: ~
  apiUrlBrowser: ~
  image:
    repository: "chart-example.local/cwa/pwa"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

# You may prefer using the managed version in production: https://mercure.rocks
mercure:
  publicUrl: https://chart-example.local/.well-known/mercure
  extraDirectives: cors_origins http://chart-example.local https://chart-example.local
  corsOrigin: '*'
  jwtKey:
    subscriber:
      key: 'my-key-that-must-be-at-least-256-bits'
      algorithm: ~
    publisher:
      key: 'my-key-that-must-be-at-least-256-bits'
      algorithm: ~

# Full configuration: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  enabled: true
  # If bringing your own PostgreSQL, the full uri to use
  #url: postgresql://cwa:!ChangeMe!@database:5432/api?serverVersion=13&charset=utf8
  global:
    postgresql:
      auth:
        username: "example"
        password: "!ChangeMe!"
        database: "api"
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  primary:
    persistence:
      enabled: false
      storageClass: standard
      size: 1Gi
    pullPolicy: IfNotPresent
    image:
      repository: bitnami/postgresql
      tag: 14
    resources:
      requests:
        memory: 50Mi
        cpu: 10m

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube.
  limits:
    cpu: 700m
    memory: 800Mi
  requests:
    cpu: 501m
    memory: 600Mi

# If you use Mercure, you need the managed or the On Premise version to deploy more than one pod: https://mercure.rocks/docs/hub/cluster
replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
