overrides:
  tar-fs: '>=3.0.7'
  ws: '>=8.21.0'
auditConfig:
  ignoreCves: []
shamefullyHoist: true
strictPeerDependencies: false
minimumReleaseAge: 0
confirmModulesPurge: false
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  vue-demi: true
