apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cwa.fullname" . }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
data:
  php-app-env: {{ .Values.php.appEnv | quote }}
  php-app-debug: {{ .Values.php.appDebug | quote }}
  php-cors-allow-origin: {{ .Values.php.corsAllowOrigin | quote }}
  php-trusted-hosts: {{ .Values.php.trustedHosts | quote }}
  php-trusted-proxies: "{{ join "," .Values.php.trustedProxies }}"
  php-mercure-jwt-algorithm: {{ .Values.php.mercure.jwt.algorithm | quote }}
  jwt-cookie-samesite: {{ .Values.php.jwt.samesite | quote }}
  jwt-public: {{ .Values.php.jwt.public | quote }}
  mercure-url: "http://{{ include "cwa.fullname" . }}/.well-known/mercure"
  mercure-public-url: {{ .Values.mercure.publicUrl | default "http://127.0.0.1/.well-known/mercure" | quote }}
  mercure-extra-directives: {{ .Values.mercure.extraDirectives | quote }}
  mercure-subscriber-jwt-algorithm: {{ .Values.mercure.jwtKey.subscriber.algorithm | quote }}
  mercure-publisher-jwt-algorithm: {{ .Values.mercure.jwtKey.publisher.algorithm | quote }}
  mercure-cors-origin: {{ .Values.mercure.corsOrigin | quote }}
  caddy-global-options: {{ .Values.php.caddy.globalConfig | quote }}
  api-url: {{ .Values.pwa.apiUrl | default (printf "http://%s" (include "cwa.fullname" .)) | quote }}
  api-url-browser: {{ .Values.pwa.apiUrlBrowser | default (printf "https://%s" (include "cwa.fullname" .)) | quote }}
  mailer-email: {{ .Values.php.mailer.email | quote }}
  gcloud-bucket: {{ .Values.php.gcloud.bucket | quote }}
  database-ssl-mode: {{ .Values.php.databaseSSL.mode | quote }}
  cache-url: http://{{ include "cwa.fullname" . }}:2019/souin-api/souin
