{{- $fullName := include "cwa.fullname" . -}}
{{- $primaryHost := index .Values.ingress.hosts 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cwa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cwa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cwa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          env:
            - name: BROWSER_SERVER_NAME
              value: {{ $primaryHost.host | quote }}
            - name: SERVER_NAME
              value: :80
            - name: APP_UPSTREAM
              value: {{ include "cwa.fullname" . }}-pwa:3000
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-publisher-jwt-key
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-subscriber-jwt-key
            - name: MERCURE_PUBLISHER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mercure-publisher-jwt-algorithm
            - name: MERCURE_SUBSCRIBER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mercure-subscriber-jwt-algorithm
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-app-env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-app-debug
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-app-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: php-cors-allow-origin
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: database-url
            - name: CADDY_GLOBAL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: caddy-global-options
            - name: MERCURE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-url
            - name: MERCURE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-public-url
            - name: MERCURE_EXTRA_DIRECTIVES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-extra-directives
            - name: MERCURE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cwa.fullname" . }}
                  key: mercure-subscriber-jwt-key
            - name: MERCURE_CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mercure-cors-origin
            - name: MERCURE_JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: php-mercure-jwt-algorithm
            - name: JWT_COOKIE_SAMESITE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: jwt-cookie-samesite
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: jwt-secret
            - name: JWT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: jwt-public
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: jwt-passphrase
            - name: MAILER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: mailer-email
            - name: MAILER_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: mailer-dsn
            - name: DATABASE_CA_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: database-ssl-ca
            - name: DATABASE_CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: database-ssl-cert
            - name: DATABASE_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: database-ssl-key
            - name: DATABASE_SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: database-ssl-mode
            - name: GCLOUD_JSON
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: gcloud-json
            - name: GCLOUD_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: gcloud-bucket
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: admin-username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: admin-password
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: admin-email
            - name: CACHE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: cache-url
            - name: VARNISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: varnish-url
            - name: VARNISH_UPSTREAM
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: varnish-upstream
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          readinessProbe:
            httpGet:
              path: /docs.jsonld
              port: http
              # request which skips the cache but ensures the API is ready
              httpHeaders:
                - name: X-Varnish
                  value: '1'
                - name: Accept
                  value: application/ld+json
            initialDelaySeconds: 8
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
