apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cwa.fullname" . }}
  labels:
    {{- include "cwa.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=16&charset=utf8" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Release.Name .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-subscriber-jwt-key: {{ .Values.mercure.jwtKey.subscriber.key | b64enc | quote }}
  mercure-publisher-jwt-key: {{ .Values.mercure.jwtKey.publisher.key | b64enc | quote }}
  jwt-secret: {{ .Values.php.jwt.secret | b64enc | quote }}
  jwt-passphrase: {{ .Values.php.jwt.passphrase | b64enc | quote }}
  mailer-dsn: {{ .Values.php.mailer.dsn | b64enc | quote }}
  database-ssl-ca: {{ .Values.php.databaseSSL.ca | quote }}
  database-ssl-cert: {{ .Values.php.databaseSSL.cert | quote }}
  database-ssl-key: {{ .Values.php.databaseSSL.key | quote }}
  gcloud-json: {{ .Values.php.gcloud.jsonKey | quote }}
  admin-username: {{ .Values.php.admin.username | b64enc | quote }}
  admin-password: {{ .Values.php.admin.password | b64enc | quote }}
  admin-email: {{ .Values.php.admin.email | b64enc | quote }}
  caddy-cdn-options: {{ .Values.php.caddyCdnOptions | quote }}
