apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: cwa
build:
  artifacts:
    - image: cwa-php
      context: ../api
      docker:
        target: app_php
    - image: cwa-app
      context: ../app
      docker:
        target: prod

deploy:
  kubeContext: minikube
  helm:
    releases:
    - name: cwa
      chartPath: ./cwa
      namespace: default
      setValueTemplates:
        php.image.repository: "{{.IMAGE_REPO_cwa_php}}"
        php.image.tag: "{{.IMAGE_TAG_cwa_php}}@{{.IMAGE_DIGEST_cwa_php}}"
        pwa.image.repository: "{{.IMAGE_REPO_cwa_app}}"
        pwa.image.tag: "{{.IMAGE_TAG_cwa_app}}@{{.IMAGE_DIGEST_cwa_app}}"
      valuesFiles:
        - skaffold-values.yaml
